### PR TITLE
Install tools from toolshed

### PR DESCRIPTION
**Pull request by abretaud**
The tools are now on the toolshed!
So a little patch to install them from there + a fix for some permission problems with volumes

### CODE REVIEW

**Comment by abretaud** [comment]
Hum, I don't understand why it fails installing the new tools: https://travis-ci.org/galaxy-genome-annotation/docker-galaxy-genome-annotation/builds/274210972#L952
It builds fine on my laptop...
Any idea maybe?

**Comment by abretaud** [comment]
Oh I see now: "no space left on device"...

**Comment by bgruening** [comment]
@abretaud try to split them into two files and try to make this dance: https://github.com/bgruening/galaxy-rna-workbench/blob/master/Dockerfile#L18

**Comment by abretaud** [comment]
Aaah green, thanks for the tip!

**Comment by bgruening** [comment]
Cool!

**Pull request merged**
