### PR TITLE
Update to 20.05

### PR DESCRIPTION
**Pull request by abretaud**
Let's see if it builds

### CODE REVIEW

**Comment by abretaud** [comment]
The travis job is killed at 2hrs, is it possible to ask travis to increase the build time limit?

**Comment by bgruening** [comment]
Yes, but 2h is already an extension. Is there some tool where conda install takes ages? Some R deps? Github actions offer 5h build-time. But this also might time out if conda resolution is the problem.

**Comment by abretaud** [comment]
Ok, I thought that 2h was the default.
I don't see a single install being much slower, it's just most of them that take some time
Maybe I'll try migrating to github actions. Anyway for now the tests would fail after the install step (https://github.com/bgruening/docker-galaxy-stable/pull/560)

**Comment by bgruening** [comment]
So nice!

**Comment by abretaud** [comment]
All green now, and tested locally, so time to merge :)

**Pull request merged**
