### PR TITLE
Update GMOD to 18.05

### PR DESCRIPTION
**Pull request by abretaud**
Finally trying to update this image...

### CODE REVIEW

**Comment by abretaud** [comment]
OMG it's green !§§!

**Comment by bgruening** [comment]
What? First try? What does this mean :)
Congrats @abretaud!

**Comment by abretaud** [comment]
> What? First try? What does this mean :)

At first I thought there was a bug in travis, but no :D

**Comment by bgruening** [comment]
:laughing: :rofl:

**Pull request merged**
